name: Test - Apps Standalone

on:
  workflow_dispatch:

  workflow_call:

jobs:
  apps-test:
    strategy:
      max-parallel: 99
      matrix:
        apps:
          - DatasetLoader@main
          - cpu_tracker_member@main
          - logged_in@main
          - ring@main
          - inbox@main
          - basic_aggregator@main
          - fl_client@main
          - fl_aggregator@main
          - pretrained_model_aggregator@main
          - pretrained_model_local@main
        python-version: ["3.9"]
        os: [ubuntu-latest, macos-latest]
        # runner: [syftbox-sh-linux-x64, scaleway-macOS-arm64]
      fail-fast: false

    # runs-on: ${{ matrix.runner }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Parse app repository info
        id: apprepo
        run: |
          REPO=$(echo ${{ matrix.apps }} | cut -d'@' -f1)
          REF=$(echo ${{ matrix.apps }} | cut -d'@' -f2)
          echo "REPO=$REPO" >> $GITHUB_OUTPUT
          echo "REF=$REF" >> $GITHUB_OUTPUT

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: OpenMined/${{ steps.apprepo.outputs.REPO }}
          ref: ${{ steps.apprepo.outputs.REF }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.4.25"

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Provisioning dummy datasite
        run: |
          CONFIG_PATH="$(pwd)/config.json"
          DATA_DIR="$(pwd)/data/"
          mkdir -p $DATA_DIR/datasites/alice@openmined.org $DATA_DIR/apps
          echo '{
              "data_dir": "'"$DATA_DIR"'",
              "server_url": "http://localhost:5001",
              "client_url": "http://localhost:8080",
              "email": "alice@openmined.org",
              "token": null,
              "email_token": null
          }' > $CONFIG_PATH
          cat $CONFIG_PATH

      - name: Run the test
        run: |
          chmod +x ./run.sh
          export SYFTBOX_CLIENT_CONFIG_PATH="$(pwd)/config.json"
          timeout 10s sh ./run.sh
          exit_code=$?
          if [ $exit_code -eq 124 ]; then
            echo "run.sh is running long as expected; marking step as success."
            exit 0
          else
            echo "run.sh exited with code $exit_code."
            exit $exit_code
          fi
